-- =============================================================================
-- Web Upgrade — guard compatibility_page_view by page, measure the bar apart
-- =============================================================================
-- Applied as migration 'web_upgrade_guard_page_view_and_bar' (in-place patch of
-- web_upgrade_performance via pg_get_functiondef + anchored replace).
--
-- Symptom: on 2026-07-30 the guide's $/session fell from $5 to $2 and its CTR
-- from 15% to 4.7% overnight, with real guide-page traffic unchanged.
--
-- Cause: at 04:25:38 UTC that day, layout/theme.liquid on the LIVE theme
-- (187483062579) started loading pesado-compatibility.js on every page, to power
-- the mobile COMPATIBILITY bar. The script fires compatibility_page_view
-- unconditionally on init, so every page of the site emitted "guide viewed" —
-- 6,043 foreign-page views in one day (first contaminated event 04:25:42, four
-- seconds after the theme edit).
--
-- Patch 1 — the ev CTE now keeps compatibility_page_view only when its
-- page_path is the guide page (blank kept for pre-field history):
--   and (action <> 'compatibility_page_view'
--        or coalesce(payload->>'page_path', '') = ''
--        or payload->>'page_path' like '%compatibility-guide%')
--   and action not like 'compatibility!_bar!_%' escape '!'
--
-- Patch 2 — a new top-level `compatibilityBar` object counts the bar's own
-- events (compatibility_bar_view / compatibility_bar_click, to be emitted by
-- the theme): views, clicks, sessions, clickSessions, ctr. The bar is excluded
-- from ev entirely: inside it, a site-wide bar view would count every page of
-- the site as an exposed module session.
--
-- Verified after applying: Guide for 2026-07-23..30 back to 1,542 sessions /
-- 2,360 views / 16.1% CTR; compatibilityBar returns zeros until the theme ships.
--
-- -----------------------------------------------------------------------------
-- 2026-07-31 · theme side shipped, both patches confirmed against live data.
--
-- The theme fix guards the event with !isStandalone rather than a URL check:
-- off the guide the script mounts an invisible `pcg--standalone` root, so that
-- flag is exact and survives any locale prefix. Bar events fire only for
-- .pesado-find-tools-mobile, once per load when it actually becomes visible;
-- the desktop orange button is deliberately NOT included — it is a different
-- surface and folding it in would corrupt the mobile bar's CTR.
--
-- Confirmed on live data:
--   * foreign-page compatibility_page_view collapsed from 433/hour to 12/hour
--     within the hour the fix landed (the tail is browsers still on the cached
--     theme, and the page_path filter neutralises it either way).
--   * every compatibility_model_select — real guide interaction — sits on a
--     path the filter keeps: /pages/compatibility-guide and
--     /en-au/pages/compatibility-guide. The filter discards no real traffic.
--   * zero compatibility_bar_view on the guide page: the bar does not render
--     there, so the two surfaces never overlap.
--   * Guide back to $5.78/session and 16.6% CTR; bar reads 783 views, 7 clicks,
--     0.9% CTR over 473 sessions.
--
-- The page_path filter STAYS regardless of the theme fix: it is what corrects
-- the contaminated history, and it is the defence if the guard ever regresses.
